-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#12131c",
	base01 = "#090913",
	base02 = "#1c1c26",
	base03 = "#737288",
	base04 = "#c5c4dd",
	base05 = "#f6f3ff",
	base06 = "#2f2f3a",
	base07 = "#3f3f4a",

	base08 = "#a7a8ff",
	base09 = "#c0c1ff",
	base0A = "#8fcef3",
	base0B = "#79d1ff",
	base0C = "#6d6faa",
	base0D = "#007da8",
	base0E = "#387b9d",
	base0F = "#61baee",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#007da8",
	fg = "#ffffff", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#7476ff",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#9e9db5",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#c0c1ff",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#8fcef3",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#005878",
})
