git:
  commit:
    signOff: true

customCommands:
  - key: "C"
    command: "$HOME/.config/lazygit/.scripts/lazygit-ai-commit-message.sh"
    description: "Generate commit message with Opencode"
    context: "files"
    output: "terminal"
