splash = false

wallpaper {
    monitor = eDP-1
    path = /home/fufu/Pictures/Wallpapers/only_you6.jpg
    fit_mode = cover
    timeout = 7
}

wallpaper {
    monitor = 
    path = /home/fufu/Pictures/Wallpapers/only_you6.jpg
    fit_mode = cover
}


