# Documentation: http://www.musicpd.org/doc/user/


music_directory		"~/Music"
playlist_directory		"~/.mpd/playlists"
db_file			"~/.mpd/database"
state_file			"~/.mpd/state"
sticker_file			"~/.mpd/sticker.sql"

bind_to_address "127.0.0.1"
bind_to_address "/tmp/mpd_socket"
restore_paused "yes"
auto_update "yes"

# input {
#   plugin "curl"
# }

playlist_plugin {
  name "cue"
  enabled "true"
}

playlist_plugin {
  name "pls"
  enabled "true"
}

audio_output {
  type "pipewire"
  name "pipewire"
}
